### ISSUE TITLE
Forbid GET + requestBody

### ISSUE THREAD

**Issue by ioggstream** [italia/api-oas-checker#307]
## I expect

- error get+requestBody 

## Instead

- no errors

## Note

```
  request-GET-no-body:
    description: A `GET` request MUST NOT accept a request body.
    severity: error
    formats: [oas3]
    given: $.paths..get.requestBody
    then:
      function: undefined
```
