### ISSUE TITLE
Switch to Spectral aliases from yaml anchors

### ISSUE THREAD

**Issue by philsturgeon** [italia/api-oas-checker#622]
Hey, thanks for making such a great ruleset. I'm just dropping by to let you know there's a new feature in Spectral which you could use in your rules which replaces what might be a bit of a hack.

```yaml
  sec-securitySchemes-jwt:
    <<: *jwt-bcp
    given:
      - >-
        $..[securitySchemes][?(@.bearerFormat=="jwt" || @.bearerFormat=="JWT")]
```

This is a really clever solution to reduce repetition of the JSON Path, but now we've got [Aliases](https://meta.stoplight.io/docs/spectral/e5b9616d6d50c-custom-rulesets#aliases) you could do the same with them.

```
aliases:
  JwtBcp:
    - "$..[securitySchemes][?(@.bearerFormat=="jwt" || @.bearerFormat=="JWT")]"
```

Then reference it like this:

```
    rules:
      foo:
        given: "#JwtBcp"
```

🙌
